In [2]:
import pandas as pd

df = pd.read_csv("European_Bank.csv")

In [3]:
df.head()

,Year,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,2025,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2025,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,2025,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,2025,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,2025,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
df.shape

(10000, 14)

In [7]:
df.columns

Index(['Year', 'CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender',
       'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [8]:
df.info

<bound method DataFrame.info of       Year  CustomerId    Surname  CreditScore Geography  Gender  Age  Tenure  \
0     2025    15634602   Hargrave          619    France  Female   42       2
1     2025    15647311       Hill          608     Spain  Female   41       1
2     2025    15619304       Onio          502    France  Female   42       8
3     2025    15701354       Boni          699    France  Female   39       1
4     2025    15737888   Mitchell          850     Spain  Female   43       2
...    ...         ...        ...          ...       ...     ...  ...     ...
9995  2025    15606229   Obijiaku          771    France    Male   39       5
9996  2025    15569892  Johnstone          516    France    Male   35      10
9997  2025    15584532        Liu          709    France  Female   36       7
9998  2025    15682355  Sabbatini          772   Germany    Male   42       3
9999  2025    15628319     Walker          792    France  Female   28       4

        Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0          0.00              1          1               1        101348.88
1      83807.86              1          0               1        112542.58
2     159660.80              3          1               0        113931.57
3          0.00              2          0               0         93826.63
4     125510.82              1          1               1         79084.10
...         ...            ...        ...             ...              ...
9995       0.00              2          1               0         96270.64
9996   57369.61              1          1               1        101699.77
9997       0.00              1          0               1         42085.58
9998   75075.31              2          1               0         92888.52
9999  130142.79              1          1               0         38190.78

      Exited
0          1
1          0
2          1
3          0
4          0
...      ...
9995       0
9996       0
9997       1
9998       1
9999       0

[10000 rows x 14 columns]>

In [9]:
df.describe()

,Year,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.0,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,2025.0,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,0.0,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,2025.0,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2025.0,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,2025.0,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,2025.0,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,2025.0,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [1]:
import pandas as pd

df = pd.read_csv("European_Bank.csv")

print(df.dtypes)

Year                 int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object